# Generated by Django 6.0 on 2026-01-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('project_type', models.CharField(choices=[('personal', 'Personal Project'), ('academic', 'Academic Project'), ('freelance', 'Freelance')], default='personal', max_length=50)),
                ('technologies', models.CharField(help_text='Technologies used, comma separated', max_length=200)),
                ('description', models.TextField()),
                ('github_link', models.URLField(blank=True)),
                ('live_link', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
