# Generated by Django 6.0 on 2026-01-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('profile_picture', models.URLField(blank=True, help_text='URL to profile picture')),
            ],
            options={
                'verbose_name': 'Bio',
                'verbose_name_plural': 'Bio',
            },
        ),
    ]
