# Generated by Django 6.0 on 2026-01-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('organization', models.CharField(max_length=200)),
                ('experience_type', models.CharField(choices=[('professional', 'Professional'), ('academic', 'Academic'), ('internship', 'Internship')], default='academic', max_length=50)),
                ('start_date', models.CharField(max_length=50)),
                ('end_date', models.CharField(blank=True, default='Present', max_length=50)),
                ('description', models.TextField()),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Experience',
                'ordering': ['order'],
            },
        ),
    ]
