# Generated by Django 6.0 on 2026-01-26 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('programming', 'Programming Languages'), ('frameworks', 'Frameworks & Libraries'), ('tools', 'Tools & Technologies'), ('soft', 'Soft Skills')], max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description of proficiency')),
            ],
            options={
                'ordering': ['category', 'name'],
            },
        ),
    ]
